WARNINGS=-Wall -Wextra -Wfloat-equal -Wundef -Wshadow -Wpointer-arith -Wstrict-overflow=5 -Wwrite-strings -Wcast-qual -Wswitch-default -Wswitch-enum -Wconversion -Wunreachable-code -Winit-self -Werror-implicit-function-declaration -Wno-unused-result

all: 
	g++ -g -std=c++14 -static -pipe $(WARNINGS) -o build/Partition.out src/Partition.cpp 
